# Generated by Django 5.0.7 on 2024-07-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdescription',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book_list.book'),
        ),
    ]
